### ISSUE TITLE
[SUGGESTION] Avoid the "reinvent the wheel" issue

### ISSUE THREAD

**Issue by MarcoRavich** [ivcained/DDAW#1]
Hi there, this project "sounds" very interesting (due to your awesome skills too) so we wanna suggest you to check the [DAWs page page](https://github.com/forart/HyMPS/blob/main/DAWs.md#---) under the [AUDIO section](https://github.com/forart/HyMPS#-) of our [HyMPS project](https://github.com/forart/HyMPS#readme): we've collected - and sorted - those open source projects in order to push their evolution by favouring collaborations between developers (and not only).

Anyway, as you can see, some of them are unfortunally in a deadlock state due to the inherent difficulties in developing and maintaining a DAW.

That's why we strongly encourage you to carefully check if is possible to reuse already developed libs/code in your project.

Hope that helps/inspires !

**Comment by ivcained** [comment]
I appreciate it a lot @forart 
Thank you for sharing links to these projects, definitely useful!
